Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NegatedIf:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Blocks:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Rails/Output:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
